### PR TITLE
(feature) Sort TP folders according to slides

### PR DESCRIPTION
**Pull request by parsyval**
Add a number before every folder in TP according to the slides.
Also fixed typos in docs/markdown/directive/exercice_directive_use.md and docs/markdown/forms/template-friven-form/exercice_create_form.md

### CODE REVIEW

**Comment by Xartok** [comment]
@parsyval I didn't find any change since previous commit 63096db in [exercice_directive_use](https://github.com/sfeir-open-source/sfeir-school-angular/blob/folder-sort/docs/markdown/directive/exercice_directive_use.md) nor in [exercice_create_form](https://github.com/sfeir-open-source/sfeir-school-angular/blob/folder-sort/docs/markdown/forms/template-driven-forms/exercice_create_form.md), are you sure you pushed these changes ?

**Comment by ValentinParsy** [comment]
Arf right, I forgot to push these sry, it's on now.

**Comment by kuroidoruido** [comment]
You rename all TP directories but not the according slide steps.
You should also rename the TP indication in every exercise slides and solution slides. You should change the forlder pattern on the slide "Déroulement des exercices"

**Comment by ValentinParsy** [comment]
Done, I'll fix the conflicts after #7 is merged

**Comment by kuroidoruido** [comment]
> @Nicoss54 @kuroidoruido Done, I'll fix the conflicts after #7 is merged

You can fix conflict, the #7 PR is merged :slightly_smiling_face:

**Pull request merged**
