### PR TITLE
chore(CI): add CI support via builtin github actions

### PR DESCRIPTION
**Pull request by tinesoft**
With this PR, `npm run test` on `TP/` folder, will be automatically performed by Github (via Actions) on each commit , ensuring better integration of future contributions.

### CODE REVIEW

**Comment by tinesoft** [comment]
Note: current test failures of the [TP CI Action](https://github.com/sfeir-open-source/sfeir-school-angular/pull/7/checks?check_run_id=480952226) have already been addressed in #6/

**Comment by kuroidoruido** [comment]
@ValentinParsy I think this PR should be merged before yours #28 to simpler merge process :slightly_smiling_face:

**Comment by kuroidoruido** [comment]
I made a lot of fix to the tests to make them run. This PR will let us verify all TP are building and all unit tests run. It will ensure some basic quality of ours PRs

**Comment by Nicoss54** [comment]
For me it's good, well done for the job and thanks

After resolving conflicts, it's good for me

**Review by Nicoss54 — CHANGES_REQUESTED** [review]
Just resolve the conflict and it will be good to me :)

**Comment by kuroidoruido** [comment]
@Nicoss54 I resolved conflict, so you can rebase and merge when you will be ready :slightly_smiling_face:

**Review by Nicoss54 — APPROVED** [review]

**Pull request merged**
